### ISSUE TITLE
Problem trying to swap the Iotex to IotexE tokens

### ISSUE THREAD

**Issue by MicaelG** [iotexproject/iotex-explorer#1072]
I had a problem trying to swap the Iotex to IotexE tokens. I tried a few times and none was successful, then I looked at the Txid and realized that the contract for which this exchange is configured is incorrect and tried to do the iopay wallet manually and got it, and due to unsuccessful attempts using the iotex geeks wallet My funds are pending txid and I am unable to trade my currencies.
![iotex issue](https://user-images.githubusercontent.com/51017035/66736722-6321fc00-ee40-11e9-90c4-325a8b457222.JPG)
![iotex issue 2](https://user-images.githubusercontent.com/51017035/66736727-67e6b000-ee40-11e9-895d-71a39341fc79.JPG)
![iotex issue 3](https://user-images.githubusercontent.com/51017035/66736728-687f4680-ee40-11e9-9b5b-2fe1e372ca10.JPG)
![iotex issue 4](https://user-images.githubusercontent.com/51017035/66736729-687f4680-ee40-11e9-937a-462fce44a700.JPG)

**Comment by puncsky** [comment]
@dustinxie could you help check the tx?

**Comment by dustinxie** [comment]
@MicaelG , thx for reporting the issue
1. the first tx failed, as you found out, due to using outdated contract.
2. the second tx "aa6657fe4dd48ac6b775f73958ed44d9778e149037ad7db328ca84fa300ad355" succeeded, and 1020 native token are converted to 1020 IotexE, and sent to Ether address "0x1a18c7163b1c2d969b69ca70bbc3648658702cd2" in tx https://etherscan.io/tx/0x30a95c1674e794ecf77600b76b4958aa7393a3de6e33740a9c7277f8f03d680f

**Comment by MicaelG** [comment]
Thank`s I solved my Problem. :)
