### ISSUE TITLE
contract IOTX transfer is not supported in this case, please help! 

### ISSUE THREAD

**Issue by bf945** [iotexproject/iotex-explorer#1744]
In this transaction, around 10000 IOTX were transferred as the result of contract execution. But it does not reflect on this page. Please help and prioritize. This affect our user experience. Thanks!
 
https://iotexscan.io/action/3bdc1a5ad1b226d7a88d38571a45fefa0f115d171e0e6280129f95fe1db687c3

**Comment by AirdropAnalyst** [comment]
Same bro

**Comment by guo** [comment]
OK. We are looking into this! Thanks for reporting!

**Comment by CoderZhi** [comment]
This is a frontend bug. You may find the transaction information under the recipient address https://iotexscan.io/address/io1093xdq9npuf6r4wrva602xqaf6tam2exjrx7pw. Our engineers are working on the issue and will launch a fix version soon.

**Comment by CoderZhi** [comment]
@uu-z The root cause is here: https://github.com/iotexproject/iotex-explorer/blob/053e391c4305a179a132fed6180d83f926eb1c21/src/shared/pages/action-detail-page.tsx#L163
instead of using the return value of execution, we should query https://github.com/iotexproject/iotex-explorer/blob/a0168f9a2ae39758a626b2b88211072e277fbe3b/src/shared/queries.ts#L578-L581
