### ISSUE TITLE
Failed Transaction

### ISSUE THREAD

**Issue by Netvines** [iotexproject/iotex-explorer#1915]
A BSC wallet address was used to send out BNB bsc but while carrying out the transaction the address was changed to another iotx address and the coin was not delivered to the recipient wallet. At this point now it has not reflected in my wallet , here is the hash:

**Comment by Netvines** [comment]
47270f6d5fe2c2d97ed7d8e8a5d808a37b5db5b282cb2dd85ea767890068ed92

**Comment by jrynkiew** [comment]
Hi Netvines,

The 0x address in your ioPay app does not mean that it supports native BSC or Ethereum coins. Just in the same way, simply providing an Ethereum or Binance Smart Chain account into a transaction does mean that the tokens will be sent to those chains. 

The tokens you sent did not fail to transfer - they are in the delivery address, but on IoTeX chain, not on BSC chain. If you have the private key of that target delivery address, you can import it into ioPay and recover them. 

Since the issues described here are not with iotex-explorer, but most likely you sending the tokens to the wrong chain, I am closing this issue. If you need support on this matter, please contact support@iotex.io by e-mail.

**Comment by Netvines** [comment]
But my trust wallet only has seed phrase which is not working while I try
to import the wallet to IOTX wallet. What do I do?

**Comment by jrynkiew** [comment]
> But my trust wallet only has seed phrase which is not working while I try to import the wallet to IOTX wallet. What do I do?

Follow this guide. https://community.iotex.io/t/migrate-your-iotex-wallet-from-trust-wallet-to-iopay/2352 

This is not the correct place to contact support on these kind of issues, instead please contact support@iotex.io by e-mail.
