### ISSUE TITLE
Transaction not received 

### ISSUE THREAD

**Issue by guillaume57** [iotexproject/iotex-explorer#1924]
hello

I have a problem with one of my transactions

hash::     dd8fd8682afcb334a1a262b9268a0d8b00af3ec35a84eb898ab2558b82d6012a

from  io1hy056gz5dq4hn2n9fcp2cwhdx6r3cj3jcy4fs2

to eth 0xBC3cB84bB7B3AbD9A845b3466A62f587AC26b83C convert io1hs7tsjahkw4an2z9kdrx5ch4s7kzdwpuy6cgcq

help me please

**Comment by mehmettugsat** [comment]
same for me. What the hell is this?

**Comment by guillaume57** [comment]
Hello
I sent an email to support I'm waiting for an answer

support@iotex.io

**Comment by mehmettugsat** [comment]
Hi, i also send now an email to their support. But, i dont know.

**Comment by guillaume57** [comment]
if you sent is worth bottom to coinbase i just found these

https://community.iotex.io/t/instructions-depositing-withdrawing-iotx-with-coinbase/3090

**Comment by guillaume57** [comment]
Hello

for my part sending from iopay wallet to coinbase I got this response from iotex

Unfortunately, if you sent from ioPay wallet directly to Coinbase,
the tokens have been sent to the same address, but on a different blockchain.
Since Coinbase uses Ethereum chain IOTX-E tokens, it expected you to deposit Ethereum based IOTX instead of native IOTX tokens. So you essentially sent tokens to the same address as your Coinbase displayed address, but on IoTeX blockchain, so unless Coinbase recovers these tokens for you, you cannot recover them

**Comment by jrynkiew** [comment]
Hi,
Sorry for your loss, but these issues all seem to relate to sending tokens to the wrong chain, which in many cases cannot be recovered without contacting Coinbase/other exchanges directly.

Since the issues described here are not with iotex-explorer, but most likely you sending the tokens to the wrong chain, I am closing this issue. If you need support on this matter, please contact support@iotex.io by e-mail.
