### ISSUE TITLE
my mistake i thiunk

### ISSUE THREAD

**Issue by rcozza21** [iotexproject/iotex-explorer#1931]
4a2153a528acfd2fc1543f404b003a8e5ae056b45f5dff3e46983e49f47dac96

the eth was supposed to go to this address

0xeb67506423091f005e3628c1e99cc6d909fdb315

**Comment by jrynkiew** [comment]
Hi rcozza21,
 
The issue is not with iotex-explorer, but most likely you sent the tokens to the wrong chain. The tokens you talk about did in fact go to the specified address, but on the IoTeX chain, and if you wanted to send them to a wallet which expects native Ethereum tokens, then you might have lost those tokens - and you will have to work with that wallet/exchange to recover them. If you need further support on this matter, please contact support@iotex.io by e-mail, providing all necessary background information about the transaction.
