### ISSUE TITLE
Issue Transfering IOTX from MEW to ioPay Wallet

### ISSUE THREAD

**Issue by pasrkb** [iotexproject/iotex-explorer#1934]
I set up an ioPay Desktop v1.0.16 wallet and tried to send IOTX from MEW to the ioPay wallet. MEW keeps telling me that the address: io1zz49mkxvdm8n2rg0fv8kxtfu4h3yadqa76vf78 is an Invalid Address. Please advise.
[IOTX transfer from MEW to ioPay Wallet Invalid Address screen shot 11-13-21.docx](https://github.com/iotexproject/iotex-explorer/files/7533065/IOTX.transfer.from.MEW.to.ioPay.Wallet.Invalid.Address.screen.shot.11-13-21.docx)

**Comment by jrynkiew** [comment]
Hi pasrkb,

Hi jorgecrypto9 ,

The issue is not with iotex-explorer, but instead in the way IoTeX handles interacting with web3 tools. FYI, you should not try sto send IOTX-E (Ethereum based IOTX tokens from MyEtherWallet to your ioPay, since ioPay doesn't support Ethereum chain tokens. You need to send native IOTX ONLY to this address). If you need support on this matter, please contact support@iotex.io by e-mail.
