### ISSUE TITLE
Explorer returns error when blockchain height is 0

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#199]
<img width="1680" alt="Screen Shot 2019-04-04 at 6 38 46 AM" src="https://user-images.githubusercontent.com/35021395/55560186-92db9480-56a4-11e9-9746-689f7969c46c.png">

**Comment by puncsky** [comment]
<img width="832" alt="Screen Shot 2019-04-04 at 8 32 46 PM" src="https://user-images.githubusercontent.com/1387285/55602116-d40d8c00-5718-11e9-90cf-26c058783630.png">

https://iotexscan.io/block/578923e5fa324d9f508cafa750bd929895edab8f603a85bbf3c59228fc849621

in block details page, let's make it support two queries:

1. GET /block/:height, if the height is an integer, then getBlockMetas byIndex [height, height]
1. GET /block/:hash, if the hash is hex and length in 64, getBlockMetas byHash
1. otherwise, display NotFound component
