### ISSUE TITLE
switching network provider should change the graphql endpoint as well

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#664]

**Comment by puncsky** [comment]
sorry that I forgot to add the scope that let's do this only in the wallet.

**Comment by nmhung1210** [comment]
> sorry that I forgot to add the scope that let's do this only in the wallet.
There is a problem that users might be confused about the network for actions/blocks page as well. The use-case is that users switch to a network and then make some transaction and then click on the action hash link to the action page to check detail. So I think it's better to keep the switch of the network affecting globally instead of limit in wallet scope.
